id = "robot-framework"
name = "Robot Framework"
version = "0.0.1"
schema_version = 1
authors = ["JosÃ© Mendes <mendesfilho@pm.me>"]
description = "ðŸ¤– Robot Framework support."
repository = "https://github.com/mendes-jose/zed-robot.git"

[grammars.robot]
repository = "https://github.com/Hubro/tree-sitter-robot"
rev = "e34def7cb0d8a66a59ec5057fe17bb4e6b17b56a"
