id = "robot"
name = "Robot Framework"
description = "ðŸ¤– Robot Framework support."
authors = ["JosÃ© Mendes <mendesfilho@pm.me>"]
version = "0.0.0"
schema_version = 1

[grammars.robot]
# tree-sitter repo URL and a commit SHA in `rev`.
repository = "https://github.com/Hubro/tree-sitter-robot" # <-- update me
rev = "e34def7cb0d8a66a59ec5057fe17bb4e6b17b56a"

# If you have a local clone and want to use it for development:
# rev = "HEAD"
